export const defaultCatalogCourses = [
  {
    slug: 'java',
    title: 'Java Programming Mastery',
    subtitle: 'Core Java, OOP & Spring Boot',
    description: 'Build strong software engineering fundamentals with Java. Master object-oriented design, collections, multithreading, JDBC, REST APIs, and enterprise-grade Spring Boot services.',
    syllabus: ['Java syntax, JVM, JDK & tooling', 'Object-Oriented Programming and SOLID design', 'Collections, generics, exceptions and streams', 'Multithreading, concurrency and executors', 'JDBC, Hibernate and database integrations', 'Spring Boot REST APIs and deployment basics'],
    duration: '76 Hours of Content',
    rating: 4.8,
    modulesCount: 10,
    badge: 'Career Ready',
    accent: 'rose',
    actionUrl: null,
    published: true
  },
  {
    slug: 'data-science',
    title: 'Data Science Professional',
    subtitle: 'Python, Statistics & Machine Learning',
    description: 'Turn raw datasets into business insight and predictive models using Python, statistics, visualization, feature engineering, Scikit-Learn, and end-to-end notebooks.',
    syllabus: ['Python data science workflow setup', 'Statistics, probability and hypothesis testing', 'NumPy, Pandas and data cleaning pipelines', 'Exploratory analysis and data visualization', 'Regression, classification and model evaluation', 'Capstone model with reporting dashboard'],
    duration: '88 Hours of Content',
    rating: 4.9,
    modulesCount: 10,
    badge: 'High Demand',
    accent: 'cyan',
    actionUrl: null,
    published: true
  },
  {
    slug: 'data-analytics',
    title: 'Data Analytics Bootcamp',
    subtitle: 'Excel, SQL, Power BI & Dashboards',
    description: 'Learn practical analytics for real business teams. Clean data, write SQL queries, build KPI dashboards, automate reports, and present insights with confidence.',
    syllabus: ['Advanced Excel formulas and pivot workflows', 'SQL filtering, joins, grouping and window functions', 'Data cleaning and validation techniques', 'Power BI dashboards and DAX foundations', 'Business metrics, funnels and cohort analysis', 'Executive storytelling and insight presentation'],
    duration: '64 Hours of Content',
    rating: 4.8,
    modulesCount: 10,
    badge: 'Job Focused',
    accent: 'emerald',
    actionUrl: null,
    published: true
  },
  {
    slug: 'mern-stack',
    title: 'MERN Stack Development',
    subtitle: 'MongoDB, Express, React & Node.js',
    description: 'Ship full-stack JavaScript applications using MongoDB, Express, React, and Node.js with authentication, API architecture, deployment, and production-ready project workflows.',
    syllabus: ['Modern JavaScript and Node.js fundamentals', 'Express routing, middleware and REST APIs', 'MongoDB schema design and Mongoose models', 'React components, hooks and state management', 'Authentication, authorization and secure sessions', 'Full-stack deployment and production debugging'],
    duration: '84 Hours of Content',
    rating: 4.9,
    modulesCount: 10,
    badge: 'Full Stack',
    accent: 'emerald',
    actionUrl: null,
    published: true
  },
  {
    slug: 'python',
    title: 'Python Programming Foundation',
    subtitle: 'Automation, APIs & Problem Solving',
    description: 'Start from Python fundamentals and grow into automation, scripting, APIs, file handling, data workflows, and clean coding practices for real-world engineering tasks.',
    syllabus: ['Python syntax, functions and control flow', 'Data structures, modules and virtual environments', 'File handling, JSON and CSV automation', 'Object-oriented Python and reusable packages', 'API consumption with requests and FastAPI basics', 'Automation projects and interview problem solving'],
    duration: '58 Hours of Content',
    rating: 4.8,
    modulesCount: 10,
    badge: 'Beginner Friendly',
    accent: 'amber',
    actionUrl: null,
    published: true
  },
  {
    slug: 'cpp',
    title: 'C++ Programming & DSA',
    subtitle: 'Modern C++, STL & Competitive Logic',
    description: 'Master modern C++ with memory management, STL, algorithmic thinking, data structures, object-oriented design, and coding interview practice.',
    syllabus: ['C++ syntax, compilation and memory model', 'Pointers, references and resource management', 'OOP, templates and modern C++ patterns', 'STL containers, iterators and algorithms', 'Arrays, strings, trees, graphs and dynamic programming', 'Coding interview drills and timed assessments'],
    duration: '72 Hours of Content',
    rating: 4.8,
    modulesCount: 10,
    badge: 'Interview Track',
    accent: 'indigo',
    actionUrl: null,
    published: true
  },
  {
    slug: 'frontend',
    title: 'Frontend Engineering',
    subtitle: 'HTML, CSS, JavaScript & React',
    description: 'Create polished, responsive user interfaces with semantic HTML, modern CSS, JavaScript, React components, design systems, animations, and accessibility.',
    syllabus: ['Semantic HTML, forms and accessibility', 'Responsive CSS, Grid, Flexbox and Tailwind', 'JavaScript DOM, events and async patterns', 'React components, hooks and reusable UI', 'State management and API integrations', 'Performance, accessibility and UI testing'],
    duration: '66 Hours of Content',
    rating: 4.8,
    modulesCount: 10,
    badge: 'UI Track',
    accent: 'cyan',
    actionUrl: null,
    published: true
  },
  {
    slug: 'backend',
    title: 'Backend Development',
    subtitle: 'APIs, Databases & System Design',
    description: 'Design reliable backend systems with REST APIs, authentication, databases, caching, queues, testing, observability, and deployment-ready service architecture.',
    syllabus: ['HTTP, REST standards and API contracts', 'Authentication, roles and secure sessions', 'SQL and NoSQL database modeling', 'Caching, queues and background jobs', 'Testing, logging and error handling', 'Deployment, monitoring and system design basics'],
    duration: '78 Hours of Content',
    rating: 4.8,
    modulesCount: 10,
    badge: 'Server Side',
    accent: 'amber',
    actionUrl: null,
    published: true
  },
  {
    slug: 'devops',
    title: 'DevOps Engineering',
    subtitle: 'Linux, Docker, CI/CD & Kubernetes',
    description: 'Learn the operational side of software delivery with Linux, Git workflows, Docker images, CI/CD pipelines, cloud deployment, Kubernetes, and monitoring.',
    syllabus: ['Linux shell, permissions and server basics', 'Git branching and release workflows', 'Docker images, containers and compose files', 'CI/CD pipelines and automated quality gates', 'Kubernetes workloads, services and config maps', 'Monitoring, logs and incident response basics'],
    duration: '80 Hours of Content',
    rating: 4.7,
    modulesCount: 10,
    badge: 'Cloud Ready',
    accent: 'purple',
    actionUrl: null,
    published: true
  },
  {
    slug: 'cloud-computing',
    title: 'Cloud Computing',
    subtitle: 'AWS, Azure & Scalable Infrastructure',
    description: 'Build a strong cloud foundation with compute, storage, networking, IAM, serverless, databases, deployment patterns, and cost-aware architecture.',
    syllabus: ['Cloud fundamentals and shared responsibility', 'Compute, storage and networking services', 'IAM, security groups and access policies', 'Managed databases and backup strategies', 'Serverless functions and event-driven design', 'Scalable architecture, monitoring and cost control'],
    duration: '74 Hours of Content',
    rating: 4.7,
    modulesCount: 10,
    badge: 'Infrastructure',
    accent: 'cyan',
    actionUrl: null,
    published: true
  },
  {
    slug: 'cybersecurity',
    title: 'Cybersecurity Essentials',
    subtitle: 'Networks, Web Security & Ethical Hacking',
    description: 'Understand practical security foundations including networking, Linux, cryptography, web vulnerabilities, secure coding, incident response, and ethical testing methods.',
    syllabus: ['Networking, ports, protocols and threat models', 'Linux security and command-line investigation', 'Cryptography, hashing and secure storage', 'OWASP Top 10 and web vulnerability testing', 'Secure coding and authentication hardening', 'Incident response, reporting and lab practice'],
    duration: '70 Hours of Content',
    rating: 4.8,
    modulesCount: 10,
    badge: 'Security Track',
    accent: 'rose',
    actionUrl: null,
    published: true
  },
  {
    slug: 'mobile-development',
    title: 'Mobile App Development',
    subtitle: 'React Native, APIs & App Deployment',
    description: 'Build cross-platform mobile applications with React Native, navigation, device APIs, offline storage, authentication, performance tuning, and app store deployment basics.',
    syllabus: ['React Native setup and component foundations', 'Navigation, layouts and responsive mobile UI', 'API integration, auth flows and secure storage', 'Camera, location and device capability APIs', 'Offline persistence and performance optimization', 'Build signing, release and app store submission'],
    duration: '76 Hours of Content',
    rating: 4.8,
    modulesCount: 10,
    badge: 'App Builder',
    accent: 'emerald',
    actionUrl: null,
    published: true
  },
  {
    slug: 'ui-ux-design',
    title: 'UI/UX Design',
    subtitle: 'Figma, Research & Product Interfaces',
    description: 'Design useful digital products with user research, information architecture, wireframes, visual systems, prototyping, usability testing, and developer-ready handoff.',
    syllabus: ['User research, personas and journey mapping', 'Information architecture and user flows', 'Wireframes, layout systems and responsive thinking', 'Visual design, typography and color systems', 'Figma components, variants and interactive prototypes', 'Usability testing and developer handoff'],
    duration: '60 Hours of Content',
    rating: 4.7,
    modulesCount: 10,
    badge: 'Design Track',
    accent: 'rose',
    actionUrl: null,
    published: true
  },
  {
    slug: 'sql-database',
    title: 'SQL & Database Engineering',
    subtitle: 'SQL, PostgreSQL & Data Modeling',
    description: 'Learn database foundations with SQL queries, relational modeling, indexes, transactions, stored procedures, performance tuning, and production PostgreSQL workflows.',
    syllabus: ['Relational database concepts and schema design', 'SELECT queries, filters, joins and aggregations', 'Indexes, constraints and query planning', 'Transactions, isolation and data consistency', 'Views, stored procedures and reporting queries', 'PostgreSQL administration and performance tuning'],
    duration: '62 Hours of Content',
    rating: 4.8,
    modulesCount: 10,
    badge: 'Database Core',
    accent: 'cyan',
    actionUrl: null,
    published: true
  },
  {
    slug: 'blockchain',
    title: 'Blockchain Development',
    subtitle: 'Web3, Solidity & Smart Contracts',
    description: 'Build blockchain fundamentals and decentralized apps with Ethereum concepts, Solidity smart contracts, wallet integrations, testing, security, and Web3 frontend flows.',
    syllabus: ['Blockchain fundamentals, wallets and transactions', 'Ethereum, gas, tokens and smart contract lifecycle', 'Solidity syntax, storage and contract patterns', 'Testing, deployment and local chain tooling', 'Web3 frontend integration and wallet auth', 'Smart contract security and audit basics'],
    duration: '68 Hours of Content',
    rating: 4.7,
    modulesCount: 10,
    badge: 'Web3 Track',
    accent: 'amber',
    actionUrl: null,
    published: true
  }
];
